# syntax=docker/dockerfile:1
services:
  redis:
    container_name: redis
    image: redis:7.4-bookworm
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - redis:/var/redis

  firehose:
    container_name: firehose
    build: .
    env_file:
      - .env
    image: aendra/xblock:latest
    depends_on:
      - redis
    command: npm run firehose

  worker:
    container_name: worker
    image: aendra/xblock-worker-gpu:latest
    ipc: host
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - firehose
    command: python3 processor/worker.py
    volumes:
      - ./model:/xblock/model
      - ./models:/xblock/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  redis:
